default: &default
  service_name: GrisDemo
  permitted_tokens: replace-me
  base_url: <%= ENV['BASE_URL'] || 'http://localhost:9292' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  permitted_tokens: <%= ENV['PERMITTED_TOKENS'] %>

